WITH QRY_HR_CARD_ALL AS  (
  SELECT 'TW' || SUBSTR(TRIM(CRDMP.STFNO), -5, LENGTH(TRIM(CRDMP.STFNO))) AS EMP_NO,
         CRDMP.CARDNO,
         REPLACE(LTRIM(REPLACE(nvl(CRDMP.cardsnsh,0),'0',' ')),' ','0') AS CARDSNSH,
         TO_NUMBER(CARDSNTH) AS CARDSNTH,
         HR.EMP_NAME,
         HR.AREA_FLAG,
         HR.DEPT_ID,
         HR.DEPT_NAME,
         CRDMP.changtm
    FROM UMEC.UM_CARD_MAP_V CRDMP, UMEC.UM_HR_EMP HR
  WHERE 'TW' || SUBSTR(TRIM(CRDMP.STFNO), -5, LENGTH(TRIM(CRDMP.STFNO))) = HR.EMP_NO
     AND HR.AREA_FLAG = 'TW'
     AND HR.ENABLE_FLAG = 'Y'
  ORDER BY CRDMP.CARDNO ASC
)
 SELECT *
 FROM QRY_HR_CARD_ALL
 WHERE CARDSNTH = :CARDSNTH
